"use client";

import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { useState } from "react";

const STAGES = [
  {
    id: "review",
    label: "Pending Review",
    color: "bg-yellow-600",
    icon: "📋",
    description: "Drafts generated by Twitter Scout, awaiting approval",
  },
  {
    id: "approved",
    label: "Approved",
    color: "bg-green-700",
    icon: "✅",
    description: "Ready to post",
  },
  {
    id: "draft",
    label: "Rejected",
    color: "bg-red-700",
    icon: "❌",
    description: "Rejected with feedback — used to improve next run",
  },
];

function DraftCard({ item }: { item: any }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const lines = item.content?.split("\n") ?? [];
  const accountLine = lines.find((l: string) => l.startsWith("Account:"));
  const account = accountLine?.replace("Account:", "").trim() ?? "";
  const draftText = lines.slice(accountLine ? 2 : 0).join("\n").trim();

  const rejectionReason = item.stage === "draft"
    ? lines.find((l: string) => l.startsWith("Rejection reason:"))?.replace("Rejection reason:", "").trim()
    : null;

  const isFounder = account.includes("Adn4n");
  const accountColor = isFounder ? "bg-blue-900 text-blue-200" : "bg-purple-900 text-purple-200";
  const accountLabel = isFounder ? "👤 @Adn4n_0" : "🐦 @lingocoins";

  const handleCopy = () => {
    navigator.clipboard.writeText(draftText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Parse title for metadata: "Draft N [@account] [style] — YYYY-MM-DD"
  const titleMatch = item.title?.match(/Draft (\d+).*\[([^\]]+)\]\s*\[([^\]]+)\]/);
  const draftNum = titleMatch?.[1] ?? "?";
  const style = titleMatch?.[2]?.replace(/@[^\]]+\]\s*\[/, "") ?? "";
  const engagement = titleMatch?.[3] ?? "";

  const date = new Date(item.createdAt).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });

  return (
    <div className="bg-gray-800 rounded-xl p-4 border border-gray-700 hover:border-gray-500 transition-all">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-gray-400">#{draftNum}</span>
          <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${accountColor}`}>
            {accountLabel}
          </span>
        </div>
        <span className="text-xs text-gray-500">{date}</span>
      </div>

      {/* Style badges */}
      {(style || engagement) && (
        <div className="flex gap-2 mb-3">
          {style && (
            <span className="text-xs px-2 py-0.5 bg-gray-700 text-gray-300 rounded">
              {style}
            </span>
          )}
          {engagement && (
            <span className={`text-xs px-2 py-0.5 rounded ${
              engagement === "high" ? "bg-green-900 text-green-300" :
              engagement === "medium" ? "bg-yellow-900 text-yellow-300" :
              "bg-gray-700 text-gray-400"
            }`}>
              {engagement} engagement
            </span>
          )}
        </div>
      )}

      {/* Draft text */}
      <div className="bg-gray-900 rounded-lg p-3 mb-3">
        <p className="text-sm text-gray-200 leading-relaxed whitespace-pre-wrap">
          {draftText || item.content}
        </p>
        <div className="flex justify-between items-center mt-2">
          <span className="text-xs text-gray-500">
            {(draftText || item.content)?.length ?? 0} / 280 chars
          </span>
          <button
            onClick={handleCopy}
            className="text-xs text-blue-400 hover:text-blue-300 transition-colors"
          >
            {copied ? "✓ Copied" : "Copy"}
          </button>
        </div>
      </div>

      {/* Rejection reason */}
      {rejectionReason && (
        <div className="bg-red-900/30 border border-red-800 rounded-lg p-3 mt-2">
          <p className="text-xs font-medium text-red-400 mb-1">Rejection reason:</p>
          <p className="text-xs text-red-200">{rejectionReason}</p>
        </div>
      )}

      {/* Title (collapsed) */}
      <div className="mt-2 pt-2 border-t border-gray-700">
        <button
          onClick={() => setExpanded(!expanded)}
          className="text-xs text-gray-500 hover:text-gray-400 transition-colors"
        >
          {expanded ? "▲ Hide details" : "▼ Show full title"}
        </button>
        {expanded && (
          <p className="text-xs text-gray-500 mt-1 break-all">{item.title}</p>
        )}
      </div>
    </div>
  );
}

export default function TwitterPage() {
  const allContent = useQuery(api.contentPipeline.getByStage, {});
  const content = allContent?.filter((c) => c.platform === "twitter");

  const byStage = STAGES.map((stage) => ({
    ...stage,
    items: content?.filter((c) => c.stage === stage.id) ?? [],
  }));

  const total = content?.length ?? 0;
  const approved = content?.filter((c) => c.stage === "approved").length ?? 0;
  const pending = content?.filter((c) => c.stage === "review").length ?? 0;
  const rejected = content?.filter((c) => c.stage === "draft").length ?? 0;

  return (
    <div className="p-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">🐦 Twitter Drafts</h1>
        <p className="text-gray-400">
          Daily drafts generated by Twitter Scout — review, approve, or reject with feedback.
        </p>
        <div className="flex gap-2 mt-3 text-xs text-gray-500">
          <span>Accounts:</span>
          <span className="bg-blue-900 text-blue-200 px-2 py-0.5 rounded-full">👤 @Adn4n_0 (founder)</span>
          <span className="bg-purple-900 text-purple-200 px-2 py-0.5 rounded-full">🐦 @lingocoins (brand)</span>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4 mb-8">
        <div className="bg-gray-900 rounded-xl p-4 border border-gray-800">
          <p className="text-sm text-gray-400 mb-1">Total Drafts</p>
          <p className="text-3xl font-bold">{total}</p>
        </div>
        <div className="bg-gray-900 rounded-xl p-4 border border-yellow-800/50">
          <p className="text-sm text-yellow-400 mb-1">📋 Pending Review</p>
          <p className="text-3xl font-bold text-yellow-300">{pending}</p>
        </div>
        <div className="bg-gray-900 rounded-xl p-4 border border-green-800/50">
          <p className="text-sm text-green-400 mb-1">✅ Approved</p>
          <p className="text-3xl font-bold text-green-300">{approved}</p>
        </div>
        <div className="bg-gray-900 rounded-xl p-4 border border-red-800/50">
          <p className="text-sm text-red-400 mb-1">❌ Rejected</p>
          <p className="text-3xl font-bold text-red-300">{rejected}</p>
          {rejected > 0 && (
            <p className="text-xs text-red-500 mt-1">Feedback applied to next run</p>
          )}
        </div>
      </div>

      {/* Board */}
      <div className="grid grid-cols-3 gap-6">
        {byStage.map((col) => (
          <div key={col.id}>
            {/* Column header */}
            <div className={`${col.color} rounded-t-xl px-4 py-3 flex items-center justify-between`}>
              <div className="flex items-center gap-2 font-semibold">
                <span>{col.icon}</span>
                <span>{col.label}</span>
              </div>
              <span className="bg-black/30 text-white text-sm font-bold px-2 py-0.5 rounded-full">
                {col.items.length}
              </span>
            </div>

            {/* Column description */}
            <div className="bg-gray-900/50 px-4 py-2 border-x border-gray-800">
              <p className="text-xs text-gray-500">{col.description}</p>
            </div>

            {/* Cards */}
            <div className="bg-gray-900/30 rounded-b-xl p-3 space-y-3 min-h-[300px] border-x border-b border-gray-800">
              {content === undefined ? (
                <div className="text-center text-gray-600 text-sm pt-8">Loading...</div>
              ) : col.items.length === 0 ? (
                <div className="text-center text-gray-600 text-sm pt-8">No drafts</div>
              ) : (
                col.items.map((item) => (
                  <DraftCard key={item._id} item={item} />
                ))
              )}
            </div>
          </div>
        ))}
      </div>

      {/* How it works */}
      <div className="mt-8 bg-gray-900/50 rounded-xl p-6 border border-gray-800">
        <h3 className="font-semibold text-gray-300 mb-3">⚙️ How the review loop works</h3>
        <div className="grid grid-cols-4 gap-4 text-sm text-gray-400">
          <div>
            <p className="text-white font-medium mb-1">1. Scout runs daily</p>
            <p>Every morning at 7am CET — Grok scans CT and generates 6 drafts</p>
          </div>
          <div>
            <p className="text-white font-medium mb-1">2. Review on Telegram</p>
            <p>Each draft lands in Telegram with ✅ Approve / ❌ Reject buttons</p>
          </div>
          <div>
            <p className="text-white font-medium mb-1">3. Feedback logged</p>
            <p>Rejections with reasons are saved — scout reads them next run</p>
          </div>
          <div>
            <p className="text-white font-medium mb-1">4. Drafts improve</p>
            <p>Scout injects past rejection reasons into its prompt — learns over time</p>
          </div>
        </div>
      </div>
    </div>
  );
}
